name: ${NODE_NAME}

filebeat.config:
  inputs:
    path: ${path.config}/prospectors.d/*.yml
    reload.enabled: false
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elk.laws.africa:9200']

setup.kibana:
  host: "http://elk.laws.africa:5601"
  protocol: "http"

xpack.monitoring.enabled: true

filebeat.modules:
  - module: nginx
    enabled: true
    access:
      var.paths: ['/mnt/log/nginx/*access.log*']
    error:
      var.paths: ['/mnt/log/nginx/*error.log*']
